spring:
  cloud:
    azure:
      servicebus:
        connection-string:
    stream:
      function:
        definition: process
      bindings:
        process-in-0:
          destination: lower-case
        process-out-0:
          destination: upper-case
      servicebus:
        bindings:
          process-in-0:
            consumer:
              auto-complete: true
          process-out-0:
            producer:
              entity-type: queue
      poller:
        fixed-delay: 1000
        initial-delay: 0
